# Generated by Django 4.2.6 on 2023-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('collections', models.CharField(choices=[('ELECTRONIC', 'Electronic'), ('FASHION', (('WOMEN', 'Women'), ('Men', 'Men'))), ('HOME APPLIANCES', 'Home Appliances'), ('VEHICLES', 'Vehicles')], default='ELECTRONIC', max_length=100)),
            ],
        ),
    ]
